---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# CHEERS 2022 Checklist App

The CHEERS 2022 statement (checklist and Explanation and Elaboration Task Force Report) replaces the 2013 CHEERS statement, which should no longer be used. The primary audiences for the CHEERS Statement are researchers reporting economic evaluations and the editors and peer reviewers assessing them for publication. While they are not intended to guide the conduct of economic evaluation, familiarity with reporting requirements will be useful for analysts when planning studies.

The new CHEERS checklist contains 28 items with accompanying descriptions. The CHEERS 2022 statement is intended to be used for any form of health economic evaluation. This includes analyses that only examine costs and cost offsets (i.e., cost analysis) or those that examine both costs and consequences (e.g., cost-effectiveness/utility analyses [CEAs/CUAs], cost-minimization, cost-benefit/benefit-cost analyses [CBAs]), and/or broader measures of benefit and harm to individuals (e.g., extended CEAs/CBAs), including measures of equity (e.g., distributional CEAs).

Those using the checklist should indicate the section of the manuscript where relevant information can be found. We recommend using a section heading with a paragraph number since referring to line or page numbers becomes confusing as repagination or line number changes occur within or after the publication process. If an item does not apply to a particular economic evaluation (e.g., items 11-13 for cost analyses, or items 16 and 22 for non-modelling studies), then checklist users are encouraged to report "Not Applicable". If information is otherwise not reported, checklist users are encouraged to write, "Not Reported". Users should avoid the term "Not conducted" as CHEERS is intended to guide and capture reporting.

## Acknowledgements

This application was developed by Hicham Moad Safhi, adapted from previous applications by Luke McGuinness, for PRISMA 2020 and the Transparency Checklist. The full source code for this application is available via the GitHub repository.
